import React from "react";
import {
  ArrowLeft,
  Download,
  Trophy,
  Brain,
  MessageSquare,
  CheckCircle2,
} from "lucide-react";

import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
  CartesianGrid,
} from "recharts";

import { CircularProgressbar, buildStyles } from "react-circular-progressbar";

import "react-circular-progressbar/dist/styles.css";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

import { useNavigate } from "react-router-dom";

function Step3Report({ report }) {

  const navigate = useNavigate();

  const {
    finalScore,
    confidence,
    communication,
    correctness,
    questionWiseScore,
  } = report;

  // ================= CHART DATA =================

  const chartData = questionWiseScore.map((item, index) => ({
    name: `Q${index + 1}`,
    score: item.score || 0,
  }));

  // ================= PERFORMANCE TEXT =================

  let performanceText = "";
  let performanceColor = "";

  if (finalScore >= 8) {
    performanceText = "Excellent Performance";
    performanceColor = "text-green-600";
  } else if (finalScore >= 5) {
    performanceText = "Good Performance";
    performanceColor = "text-yellow-500";
  } else {
    performanceText = "Needs Improvement";
    performanceColor = "text-red-500";
  }

  // ================= DOWNLOAD PDF =================

  const downloadPDF = () => {

  const doc = new jsPDF();

  // ================= COLORS =================

  const primary = [16, 185, 129];
  const dark = [31, 41, 55];
  const gray = [107, 114, 128];

  // ================= HEADER =================

  doc.setFillColor(...primary);
  doc.rect(0, 0, 220, 35, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);

  doc.text(
    "Interview Analytics Report",
    14,
    22
  );

  // ================= BASIC INFO =================

  let y = 50;

  doc.setTextColor(...dark);

  doc.setFontSize(18);

  doc.text(
    "Performance Summary",
    14,
    y
  );

  y += 14;

  doc.setFontSize(13);

  doc.text(
    `Final Score: ${finalScore}/10`,
    14,
    y
  );

  y += 10;

  doc.text(
    `Confidence: ${confidence}/10`,
    14,
    y
  );

  y += 10;

  doc.text(
    `Communication: ${communication}/10`,
    14,
    y
  );

  y += 10;

  doc.text(
    `Correctness: ${correctness}/10`,
    14,
    y
  );

  // ================= PERFORMANCE MESSAGE =================

  y += 20;

  doc.setFillColor(240, 253, 244);

  doc.roundedRect(
    14,
    y,
    180,
    28,
    4,
    4,
    "F"
  );

  doc.setTextColor(...primary);

  doc.setFontSize(13);

  let performanceMessage = "";

  if (finalScore >= 8) {

    performanceMessage =
      "Excellent interview performance with strong communication and technical clarity.";

  } else if (finalScore >= 5) {

    performanceMessage =
      "Good interview performance with minor improvements needed.";

  } else {

    performanceMessage =
      "Needs improvement in confidence, clarity, and structured answering.";

  }

  const splitMessage =
    doc.splitTextToSize(
      performanceMessage,
      165
    );

  doc.text(
    splitMessage,
    18,
    y + 12
  );

  // ================= QUESTION TABLE =================

  const tableData =
    questionWiseScore.map(
      (item, index) => [

        `Q${index + 1}`,

        item.question ||
        "No Question",

        item.answer ||
        "No Answer Submitted",

        `${item.score}/10`,

        item.feedback ||
        "No Feedback",
      ]
    );

  autoTable(doc, {

    startY: y + 45,

    head: [[
      "Question",
      "Question Title",
      "Your Answer",
      "Score",
      "AI Feedback",
    ]],

    body: tableData,

    styles: {

      fontSize: 10,

      cellPadding: 4,

      textColor: dark,

      overflow: "linebreak",

      valign: "middle",
    },

    headStyles: {

      fillColor: primary,

      textColor: [255, 255, 255],

      fontStyle: "bold",

      fontSize: 11,
    },

    alternateRowStyles: {

      fillColor: [245, 247, 250],
    },

    columnStyles: {

      0: { cellWidth: 18 },

      1: { cellWidth: 45 },

      2: { cellWidth: 65 },

      3: { cellWidth: 20 },

      4: { cellWidth: 42 },
    },
  });

  // ================= FOOTER =================

  const pageHeight =
    doc.internal.pageSize.height;

  doc.setTextColor(...gray);

  doc.setFontSize(10);

  doc.text(
    "Generated by InterviewIQ AI Platform",
    14,
    pageHeight - 10
  );

  // ================= SAVE =================

  doc.save(
    "Interview_Analytics_Report.pdf"
  );
};

  return (

    <div className="min-h-screen bg-[#f4faf7] p-6">

      {/* HEADER */}

      <div className="max-w-7xl mx-auto">

        <div className="flex items-center justify-between mb-8">

          <div className="flex items-center gap-4">

            <button
              onClick={() => navigate("/history")}
              className="w-11 h-11 rounded-full bg-white shadow-md flex items-center justify-center hover:scale-105 transition-all"
            >
              <ArrowLeft size={20} />
            </button>

            <div>
              <h1 className="text-4xl font-bold text-gray-800">
                Interview Analytics Dashboard
              </h1>

              <p className="text-gray-500 mt-1">
                AI-powered performance insights
              </p>
            </div>
          </div>

          <button
            onClick={downloadPDF}
            className="px-6 py-3 rounded-xl bg-emerald-500 hover:bg-emerald-600 text-white font-semibold shadow-lg transition-all flex items-center gap-2"
          >
            <Download size={18} />
            Download PDF
          </button>
        </div>

        {/* GRID */}

        <div className="grid lg:grid-cols-3 gap-6">

          {/* LEFT */}

          <div className="space-y-6">

            {/* SCORE CARD */}

            <div className="bg-white rounded-3xl shadow-xl p-8">

              <h2 className="text-gray-500 text-center mb-6">
                Overall Performance
              </h2>

              <div className="w-40 h-40 mx-auto">

                <CircularProgressbar
                  value={finalScore * 10}
                  text={`${finalScore}/10`}
                  styles={buildStyles({
                    textSize: "16px",
                    pathColor:
                      finalScore >= 8
                        ? "#10b981"
                        : finalScore >= 5
                        ? "#f59e0b"
                        : "#ef4444",

                    textColor:
                      finalScore >= 8
                        ? "#10b981"
                        : finalScore >= 5
                        ? "#f59e0b"
                        : "#ef4444",

                    trailColor: "#e5e7eb",
                  })}
                />
              </div>

              <div className="text-center mt-6">

                <h2
                  className={`text-2xl font-bold ${performanceColor}`}
                >
                  {performanceText}
                </h2>

                <p className="text-gray-500 mt-2">
                  AI analyzed your interview performance
                </p>
              </div>
            </div>

            {/* SKILLS */}

            <div className="bg-white rounded-3xl shadow-xl p-8">

              <div className="flex items-center gap-2 mb-6">

                <Brain className="text-emerald-500" />

                <h2 className="text-2xl font-bold">
                  Skill Evaluation
                </h2>
              </div>

              <div className="space-y-6">

                {/* CONFIDENCE */}

                <div>

                  <div className="flex justify-between mb-2">

                    <div className="flex items-center gap-2">
                      <Trophy
                        size={18}
                        className="text-emerald-500"
                      />

                      <span className="font-medium">
                        Confidence
                      </span>
                    </div>

                    <span className="font-bold text-emerald-500">
                      {confidence}
                    </span>
                  </div>

                  <div className="w-full bg-gray-200 rounded-full h-3">

                    <div
                      className="bg-emerald-500 h-3 rounded-full"
                      style={{
                        width: `${confidence * 10}%`,
                      }}
                    />
                  </div>
                </div>

                {/* COMMUNICATION */}

                <div>

                  <div className="flex justify-between mb-2">

                    <div className="flex items-center gap-2">
                      <MessageSquare
                        size={18}
                        className="text-blue-500"
                      />

                      <span className="font-medium">
                        Communication
                      </span>
                    </div>

                    <span className="font-bold text-blue-500">
                      {communication}
                    </span>
                  </div>

                  <div className="w-full bg-gray-200 rounded-full h-3">

                    <div
                      className="bg-blue-500 h-3 rounded-full"
                      style={{
                        width: `${communication * 10}%`,
                      }}
                    />
                  </div>
                </div>

                {/* CORRECTNESS */}

                <div>

                  <div className="flex justify-between mb-2">

                    <div className="flex items-center gap-2">
                      <CheckCircle2
                        size={18}
                        className="text-purple-500"
                      />

                      <span className="font-medium">
                        Correctness
                      </span>
                    </div>

                    <span className="font-bold text-purple-500">
                      {correctness}
                    </span>
                  </div>

                  <div className="w-full bg-gray-200 rounded-full h-3">

                    <div
                      className="bg-purple-500 h-3 rounded-full"
                      style={{
                        width: `${correctness * 10}%`,
                      }}
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* RIGHT */}

          <div className="lg:col-span-2 space-y-6">

            {/* GRAPH */}

            <div className="bg-white rounded-3xl shadow-xl p-8">

              <h2 className="text-2xl font-bold mb-6">
                Performance Trend
              </h2>

              <div className="h-[320px]">

                <ResponsiveContainer width="100%" height="100%">

                  <LineChart data={chartData}>

                    <CartesianGrid strokeDasharray="3 3" />

                    <XAxis dataKey="name" />

                    <YAxis domain={[0, 10]} />

                    <Tooltip />

                    <Line
                      type="monotone"
                      dataKey="score"
                      stroke="#10b981"
                      strokeWidth={4}
                    />
                  </LineChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* QUESTIONS */}

            <div className="bg-white rounded-3xl shadow-xl p-8">

              <h2 className="text-2xl font-bold mb-6">
                Question Breakdown
              </h2>

              <div className="space-y-6">

                {questionWiseScore.map((item, index) => (

                  <div
                    key={index}
                    className="border border-gray-100 rounded-2xl p-6 bg-[#f8fffb]"
                  >

                    <div className="flex items-start justify-between gap-4">

                      <div>

                        <p className="text-gray-400 text-sm mb-2">
                          Question {index + 1}
                        </p>

                        <h3 className="font-semibold text-lg text-gray-800">
                          {item.question}
                        </h3>
                      </div>

                      <div
                        className={`px-4 py-2 rounded-xl font-bold text-white
                        ${
                          item.score >= 8
                            ? "bg-green-500"
                            : item.score >= 5
                            ? "bg-yellow-500"
                            : "bg-red-500"
                        }`}
                      >
                        {item.score}/10
                      </div>
                    </div>

                    {/* FEEDBACK */}

                    <div className="mt-5 bg-green-50 border border-green-100 rounded-xl p-4">

                      <p className="text-emerald-600 font-semibold mb-1">
                        AI Feedback
                      </p>

                      <p className="text-gray-700">
                        {item.feedback}
                      </p>
                    </div>

                    {/* SCORES */}

                    <div className="grid md:grid-cols-3 gap-4 mt-5">

                      <div className="bg-white rounded-xl p-4 shadow-sm">

                        <p className="text-gray-400 text-sm">
                          Confidence
                        </p>

                        <h2 className="text-2xl font-bold text-emerald-500">
                          {item.confidence}
                        </h2>
                      </div>

                      <div className="bg-white rounded-xl p-4 shadow-sm">

                        <p className="text-gray-400 text-sm">
                          Communication
                        </p>

                        <h2 className="text-2xl font-bold text-blue-500">
                          {item.communication}
                        </h2>
                      </div>

                      <div className="bg-white rounded-xl p-4 shadow-sm">

                        <p className="text-gray-400 text-sm">
                          Correctness
                        </p>

                        <h2 className="text-2xl font-bold text-purple-500">
                          {item.correctness}
                        </h2>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Step3Report;